export const MEMBERS = [
  {
    key: "kenny",
    name: "Kenny",
    city: "California",
    tz: "America/Los_Angeles",
    title: "The Commish",
    tag: "Timezone dictator",
    bio: "Lives in the league's official timezone so he never has to convert anything. If this tool is confusing, that is policy.",
    special: "Commissioner override (does not exist)",
    taunt: "Even the elves know the bylaws better than you.",
    color: "#c9a227",
  },
  {
    key: "barbara",
    name: "Barbara",
    city: "Las Vegas",
    tz: "America/Los_Angeles",
    title: "Cinnamon Commissioner",
    tag: "Corgis have right of way",
    bio: "Christmas lives at her house. The rolls are not a side dish. They are the event. Several corgis will be in the Zoom, unmuted.",
    special: "Warm tray of rolls / +3 to morale",
    taunt: "That's not how we bowl at Christmas.",
    color: "#d45d6c",
  },
  {
    key: "jimmy",
    name: "Jimmy",
    city: "Las Vegas",
    tz: "America/Los_Angeles",
    title: "Pitmaster",
    tag: "The smoker is the clock",
    bio: "Has opinions. Has a grill. Has historically roughhoused cousin Steven. The draft starts when the bark looks right.",
    special: "Barbecue delay of game",
    taunt: "Gutter ball. That's what happens when you go soft.",
    color: "#b33b3b",
  },
  {
    key: "curt",
    name: "Curt",
    city: "Minnesota",
    tz: "America/Chicago",
    title: "4th Great-Grandnephew of a Pin",
    tag: "Ancestry.com main quest",
    bio: "Will trace this bowling lane back to 1847. Also: bees, honey, gardens. Please do not stand in the flight path.",
    special: "Pedigree chart / extra loading screen",
    taunt: "Your form is not historically accurate.",
    color: "#d4a017",
  },
  {
    key: "lynn",
    name: "Lynn",
    city: "Minnesota",
    tz: "America/Chicago",
    title: "On a first-name basis",
    tag: "Packers or nothing",
    bio: "Would never call a Packer by his last name. It's Aaron. It's Jordan. It's the guys. You know the guys.",
    special: "Pregame with Aaron (the player, not the cousin)",
    taunt: "Aaron wouldn't leave the 7-10.",
    color: "#1b7a3d",
  },
  {
    key: "timmy",
    name: "Timmy",
    city: "Minnesota",
    tz: "America/Chicago",
    title: "Grandma's favorite",
    tag: "Trains, planes, baby #3",
    bio: "Regional airline by day, train content by night, third baby incoming. Always has been grandma's favorite cousin. This is documented.",
    special: "Standby upgrade to 9am slots",
    taunt: "That's a missed approach.",
    color: "#3d7ea6",
  },
  {
    key: "bryan",
    name: "Bryan",
    city: "Wisconsin",
    tz: "America/Chicago",
    title: "Board-game endboss",
    tag: "Civil engineer / chess",
    bio: "Baseball, chess, and an undefeated record at every table game the family pretends is casual. The draft board is just another engineer's drawing.",
    special: "Always wins. Always.",
    taunt: "I already solved this lane.",
    color: "#3b6ea5",
  },
  {
    key: "amy",
    name: "Amy",
    city: "Las Vegas",
    tz: "America/Los_Angeles",
    title: "New house, old league",
    tag: "Jack may be holding the mouse",
    bio: "Jack's wife. New house. One-year-old at home. If Jack is filling this out: pick what Amy would want, which is a time that does not collide with bedtime.",
    special: "Proxy picks (commissioner is watching)",
    taunt: "The baby bowls better.",
    color: "#c46ba0",
  },
  {
    key: "jack",
    name: "Jack",
    city: "Las Vegas",
    tz: "America/Los_Angeles",
    title: "Floor man",
    tag: "Makes the machines that eat weekends",
    bio: "Works at a Las Vegas gaming company that makes slot machines. Understands RNG. Still somehow surprised by a gutter.",
    special: "Hold spin to select all (house edge applies)",
    taunt: "Tilt. Tilt. Tilt.",
    color: "#e0a325",
  },
  {
    key: "cori",
    name: "Cori",
    city: "Jacksonville",
    tz: "America/New_York",
    title: "Not Miami",
    tag: "Baby Zoe (a few months)",
    bio: "Just moved to Jacksonville from Miami. If you still say Miami, the elves will gutter you on purpose. Zoe's nap schedule is the real commissioner.",
    special: "Eastern Time, please read it twice",
    taunt: "This lane is in Florida. Not that Florida.",
    color: "#2a9d8f",
  },
  {
    key: "darien",
    name: "Darien",
    city: "Jacksonville",
    tz: "America/New_York",
    title: "Ironman, then snacks",
    tag: "Can suffer / can party",
    bio: "Will bike 112 miles and still make the draft if the snacks are good. Recovery window is a suggestion.",
    special: "Brick workout + first round",
    taunt: "That's not even a warm-up.",
    color: "#e76f51",
  },
  {
    key: "lydia",
    name: "Lydia",
    city: "Las Vegas",
    tz: "America/Los_Angeles",
    title: "Project-avoidance specialist",
    tag: "Football is the lesser renovation",
    bio: "Not a huge football fan. Extremely a fan of anything that is not a house project. This form counts as a break. You may remain seated.",
    special: "Draft in lieu of demo day",
    taunt: "You bowl like a contractor's estimate.",
    color: "#7b6b9e",
  },
  {
    key: "aaron",
    name: "Aaron",
    city: "Las Vegas",
    tz: "America/Los_Angeles",
    title: "Festival wildlife",
    tag: "Unplugs sockets / collects bans",
    bio: "Party animal. Famous for unplugging sockets at festivals and getting banned from Airbnbs. Please still pick a time. The Zoom cannot evict you. Yet.",
    special: "Noise complaint in 3… 2…",
    taunt: "Security would like a word with that throw.",
    color: "#9b2226",
  },
  {
    key: "steven",
    name: "Steven",
    city: "Phoenix",
    tz: "America/Phoenix",
    title: "Union girl dad",
    tag: "Pipe / blonde / 15-minute break",
    bio: "Union pipe fitter. Long blonde hair. Loves guns and unions. Is a girl dad, which overrules both. Phoenix does not do daylight saving, and neither does he.",
    special: "Mandated break at 6, bedtime at 7",
    taunt: "That throw was scab labor.",
    color: "#6d4c41",
  },
];
